// Code generated by "accessor -type=PhotoShare"; DO NOT EDIT.

package domain

// Id return id value
func (t PhotoShare) Id() Id {
	return t.id
}

// Title return title value
func (t PhotoShare) Title() string {
	return t.title
}
