// Code generated by "accessor -type=Photo"; DO NOT EDIT.

package domain

// Id return id value
func (t Photo) Id() Id {
	return t.id
}

// Title return title value
func (t Photo) Title() string {
	return t.title
}
