/* tslint:disable */
/* eslint-disable */
/**
 * API
 * photo-share api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPhotoSuccessResponse
 */
export interface GetPhotoSuccessResponse {
    /**
     * 投稿写真ID
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    id: string;
    /**
     * 写真タイトル
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    title: string;
    /**
     * 写真の説明
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    description: string;
    /**
     * 写真URL
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    imageUrl: string;
    /**
     * 投稿者ID
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    authorId: string;
    /**
     * カテゴリID
     * @type {string}
     * @memberof GetPhotoSuccessResponse
     */
    categoryId: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof GetPhotoSuccessResponse
     */
    createdAt: Date;
    /**
     * いいね数
     * @type {number}
     * @memberof GetPhotoSuccessResponse
     */
    likedCount: number;
}

/**
 * Check if a given object implements the GetPhotoSuccessResponse interface.
 */
export function instanceOfGetPhotoSuccessResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    if (!('description' in value)) return false;
    if (!('imageUrl' in value)) return false;
    if (!('authorId' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('likedCount' in value)) return false;
    return true;
}

export function GetPhotoSuccessResponseFromJSON(json: any): GetPhotoSuccessResponse {
    return GetPhotoSuccessResponseFromJSONTyped(json, false);
}

export function GetPhotoSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPhotoSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'imageUrl': json['imageUrl'],
        'authorId': json['authorId'],
        'categoryId': json['categoryId'],
        'createdAt': (new Date(json['createdAt'])),
        'likedCount': json['likedCount'],
    };
}

export function GetPhotoSuccessResponseToJSON(value?: GetPhotoSuccessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'authorId': value['authorId'],
        'categoryId': value['categoryId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'likedCount': value['likedCount'],
    };
}

