// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package internal

var TableNames = struct {
	Category string
	Comment  string
	Like     string
	Photos   string
}{
	Category: "category",
	Comment:  "comment",
	Like:     "like",
	Photos:   "photos",
}
