openapi: 3.0.3

info:
  description: photo-share api
  version: 1.0.0
  title: API
  contact:
    name: photo-share

tags:
  - name: photo
    description: 投稿写真関連

paths:
  /photos:
    post:
      tags:
        - photo
      summary: 投稿写真登録API
      description: 投稿写真を登録するAPIです。
      operationId: postPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPhotoRequest"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostPhotoSuccessResponse"
        "500":
          description: 失敗(Internal server error)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DomainError"

components:
  schemas:
    DomainError: # エラーレスポンス
      type: object
      properties:
        code:
          type: string
          example: 001-000001
        message:
          type: string
          example: エラーメッセージ

    PostPhotoRequest: # 投稿写真登録のリクエスト
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: 写真タイトル
          example: テスト写真タイトル
        description:
          type: string
          description: 写真の説明
          example: この写真は...
        imageUrl:
          type: string
          description: 写真URL
          example: testUrl
        authorId:
          type: string
          description: 投稿者ID
          example: testUserId
        categoryId:
          type: string
          description: カテゴリID
          example: testCategoryId

    PostPhotoSuccessResponse: # 投稿写真登録の成功レスポンス
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: 登録した写真ID
          example: photoId
