/* tslint:disable */
/* eslint-disable */
/**
 * BFF
 * photo-share bff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainError
 */
export interface DomainError {
    /**
     * 
     * @type {string}
     * @memberof DomainError
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainError
     */
    message?: string;
}

/**
 * Check if a given object implements the DomainError interface.
 */
export function instanceOfDomainError(value: object): boolean {
    return true;
}

export function DomainErrorFromJSON(json: any): DomainError {
    return DomainErrorFromJSONTyped(json, false);
}

export function DomainErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DomainErrorToJSON(value?: DomainError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

