/* tslint:disable */
/* eslint-disable */
/**
 * BFF
 * photo-share bff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPhotoRequest
 */
export interface PostPhotoRequest {
    /**
     * 写真タイトル
     * @type {string}
     * @memberof PostPhotoRequest
     */
    title: string;
    /**
     * 写真の説明
     * @type {string}
     * @memberof PostPhotoRequest
     */
    description: string;
    /**
     * 写真URL
     * @type {string}
     * @memberof PostPhotoRequest
     */
    imageUrl: string;
    /**
     * 投稿者ID
     * @type {string}
     * @memberof PostPhotoRequest
     */
    authorId: string;
    /**
     * カテゴリID
     * @type {string}
     * @memberof PostPhotoRequest
     */
    categoryId: string;
}

/**
 * Check if a given object implements the PostPhotoRequest interface.
 */
export function instanceOfPostPhotoRequest(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('description' in value)) return false;
    if (!('imageUrl' in value)) return false;
    if (!('authorId' in value)) return false;
    if (!('categoryId' in value)) return false;
    return true;
}

export function PostPhotoRequestFromJSON(json: any): PostPhotoRequest {
    return PostPhotoRequestFromJSONTyped(json, false);
}

export function PostPhotoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPhotoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'imageUrl': json['imageUrl'],
        'authorId': json['authorId'],
        'categoryId': json['categoryId'],
    };
}

export function PostPhotoRequestToJSON(value?: PostPhotoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'authorId': value['authorId'],
        'categoryId': value['categoryId'],
    };
}

