/* tslint:disable */
/* eslint-disable */
/**
 * BFF
 * photo-share bff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutPhotoSuccessResponse
 */
export interface PutPhotoSuccessResponse {
    /**
     * 編集した写真ID
     * @type {string}
     * @memberof PutPhotoSuccessResponse
     */
    id: string;
}

/**
 * Check if a given object implements the PutPhotoSuccessResponse interface.
 */
export function instanceOfPutPhotoSuccessResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function PutPhotoSuccessResponseFromJSON(json: any): PutPhotoSuccessResponse {
    return PutPhotoSuccessResponseFromJSONTyped(json, false);
}

export function PutPhotoSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPhotoSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function PutPhotoSuccessResponseToJSON(value?: PutPhotoSuccessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

