// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// DomainError defines model for DomainError.
type DomainError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// PostPhotoRequest defines model for PostPhotoRequest.
type PostPhotoRequest struct {
	// AuthorId 投稿者ID
	AuthorId string `json:"authorId"`

	// CategoryId カテゴリID
	CategoryId string `json:"categoryId"`

	// Description 写真の説明
	Description string `json:"description"`

	// ImageUrl 写真URL
	ImageUrl string `json:"imageUrl"`

	// Title 写真タイトル
	Title string `json:"title"`
}

// PostPhotoSuccessResponse defines model for PostPhotoSuccessResponse.
type PostPhotoSuccessResponse struct {
	// Id 登録した写真ID
	Id string `json:"id"`
}

// PutPhotoRequest defines model for PutPhotoRequest.
type PutPhotoRequest struct {
	// AuthorId 投稿者ID
	AuthorId string `json:"authorId"`

	// CategoryId カテゴリID
	CategoryId string `json:"categoryId"`

	// Description 写真の説明
	Description string `json:"description"`

	// Id 投稿写真ID
	Id string `json:"id"`

	// ImageUrl 写真URL
	ImageUrl string `json:"imageUrl"`

	// Title 写真タイトル
	Title string `json:"title"`
}

// PutPhotoSuccessResponse defines model for PutPhotoSuccessResponse.
type PutPhotoSuccessResponse struct {
	// Id 編集した写真ID
	Id string `json:"id"`
}

// PostPhotoJSONRequestBody defines body for PostPhoto for application/json ContentType.
type PostPhotoJSONRequestBody = PostPhotoRequest

// PutPhotoJSONRequestBody defines body for PutPhoto for application/json ContentType.
type PutPhotoJSONRequestBody = PutPhotoRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostPhotoWithBody request with any body
	PostPhotoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPhoto(ctx context.Context, body PostPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutPhotoWithBody request with any body
	PutPhotoWithBody(ctx context.Context, photoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutPhoto(ctx context.Context, photoId string, body PutPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostPhotoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPhotoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPhoto(ctx context.Context, body PostPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPhotoRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutPhotoWithBody(ctx context.Context, photoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutPhotoRequestWithBody(c.Server, photoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutPhoto(ctx context.Context, photoId string, body PutPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutPhotoRequest(c.Server, photoId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostPhotoRequest calls the generic PostPhoto builder with application/json body
func NewPostPhotoRequest(server string, body PostPhotoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPhotoRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPhotoRequestWithBody generates requests for PostPhoto with any type of body
func NewPostPhotoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/photos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutPhotoRequest calls the generic PutPhoto builder with application/json body
func NewPutPhotoRequest(server string, photoId string, body PutPhotoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutPhotoRequestWithBody(server, photoId, "application/json", bodyReader)
}

// NewPutPhotoRequestWithBody generates requests for PutPhoto with any type of body
func NewPutPhotoRequestWithBody(server string, photoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "photoId", runtime.ParamLocationPath, photoId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/photos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostPhotoWithBodyWithResponse request with any body
	PostPhotoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPhotoResponse, error)

	PostPhotoWithResponse(ctx context.Context, body PostPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPhotoResponse, error)

	// PutPhotoWithBodyWithResponse request with any body
	PutPhotoWithBodyWithResponse(ctx context.Context, photoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutPhotoResponse, error)

	PutPhotoWithResponse(ctx context.Context, photoId string, body PutPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutPhotoResponse, error)
}

type PostPhotoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostPhotoSuccessResponse
	JSON500      *DomainError
}

// Status returns HTTPResponse.Status
func (r PostPhotoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPhotoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutPhotoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PutPhotoSuccessResponse
	JSON500      *DomainError
}

// Status returns HTTPResponse.Status
func (r PutPhotoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutPhotoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostPhotoWithBodyWithResponse request with arbitrary body returning *PostPhotoResponse
func (c *ClientWithResponses) PostPhotoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPhotoResponse, error) {
	rsp, err := c.PostPhotoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPhotoResponse(rsp)
}

func (c *ClientWithResponses) PostPhotoWithResponse(ctx context.Context, body PostPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPhotoResponse, error) {
	rsp, err := c.PostPhoto(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPhotoResponse(rsp)
}

// PutPhotoWithBodyWithResponse request with arbitrary body returning *PutPhotoResponse
func (c *ClientWithResponses) PutPhotoWithBodyWithResponse(ctx context.Context, photoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutPhotoResponse, error) {
	rsp, err := c.PutPhotoWithBody(ctx, photoId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutPhotoResponse(rsp)
}

func (c *ClientWithResponses) PutPhotoWithResponse(ctx context.Context, photoId string, body PutPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*PutPhotoResponse, error) {
	rsp, err := c.PutPhoto(ctx, photoId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutPhotoResponse(rsp)
}

// ParsePostPhotoResponse parses an HTTP response from a PostPhotoWithResponse call
func ParsePostPhotoResponse(rsp *http.Response) (*PostPhotoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPhotoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostPhotoSuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest DomainError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutPhotoResponse parses an HTTP response from a PutPhotoWithResponse call
func ParsePutPhotoResponse(rsp *http.Response) (*PutPhotoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutPhotoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PutPhotoSuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest DomainError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
