// Code generated by "accessor -setter -type=User"; DO NOT EDIT.

package user

// Id return id value
func (t User) Id() ID {
	return t.id
}

// SetId set v to id
func (t *User) SetId(v ID) {
	t.id = v
}
